# Generated by Django 4.0.6 on 2022-08-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demo1.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demo1.tag'),
        ),
    ]
